#!/bin/bash

# Check if script is running as root
if [ "$EUID" -ne 0 ]; then
  echo "This script must be run as root. Re-running with sudo..."
  exec sudo "$0" "$@"
fi

# Set Windows as default
sudo bootctl set-oneshot windows.conf

# Reboot
sudo reboot
